# Generated by Django 3.2.12 on 2024-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetypes',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
