# Generated by Django 5.0.6 on 2024-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetypes', '0002_alter_expensetypes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetypes',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='expensetypes',
            name='status',
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='hierarchical_code',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='expensetypes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expensetypes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expensetypes',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='expensetypes',
            table=None,
        ),
    ]
