# Generated by Django 5.0.6 on 2024-05-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetypes', '0003_remove_expensetypes_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expensetypes',
            table='expense_types',
        ),
    ]
