# Generated by Django 5.0.6 on 2024-05-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetypes', '0004_alter_expensetypes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expensetypes',
            table='expensetypes',
        ),
    ]
