# Generated by Django 4.2.13 on 2024-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admNumber',
            field=models.CharField(max_length=255),
        ),
    ]
