# Generated by Django 3.2.10 on 2024-04-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
