# Generated by Django 4.2.14 on 2024-08-01 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('schools', '0001_initial'),
        ('feecategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCollectionsAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(max_length=50)),
                ('amountPaid', models.FloatField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('school_code', models.CharField(max_length=50)),
                ('credit', models.FloatField()),
                ('type', models.CharField(blank=True, max_length=5, null=True)),
                ('outstandingbalance', models.FloatField()),
                ('grade', models.CharField(max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('payment_mode', models.CharField(choices=[('mobile_wallet', 'Mobile Wallet'), ('Equity_bank_mobile_app', 'Equity Bank Mobile App'), ('Bank_cards', 'Bank Cards'), ('M-Pesa', 'M-Pesa'), ('Cash', 'Cash'), ('Bank_agent', 'Bank Agent'), ('Bank_over_the_counter', 'Banking Over the Counter')], max_length=50)),
                ('tran_date', models.DateField(auto_now_add=True, null=True)),
                ('feecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feecategories.feecategories')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'db_table': 'fee_collections_all',
            },
        ),
    ]
