# Generated by Django 4.2.7 on 2024-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollectionsall',
            name='debit',
        ),
        migrations.AlterField(
            model_name='feecollectionsall',
            name='amountPaid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feecollectionsall',
            name='credit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='feecollectionsall',
            name='outstandingbalance',
            field=models.FloatField(),
        ),
    ]
