# Generated by Django 4.2.7 on 2024-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfees', '0002_remove_feecollectionsall_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollectionsall',
            name='type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
