# Generated by Django 4.2.7 on 2024-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfees', '0003_alter_feecollectionsall_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollectionsall',
            name='tran_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
