# Generated by Django 4.2.7 on 2024-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfees', '0004_feecollectionsall_tran_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollectionsall',
            name='payment_mode',
            field=models.CharField(choices=[('mobile_wallet', 'Mobile Wallet'), ('Equity_bank_mobile_app', 'Equity Bank Mobile App'), ('Bank_cards', 'Bank Cards'), ('M-Pesa', 'M-Pesa'), ('Cash', 'Cash'), ('Bank_agent', 'Bank Agent'), ('Bank_over_the_counter', 'Banking Over the Counter')], max_length=50),
        ),
    ]
