# Generated by Django 3.2.25 on 2024-05-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('feecategories', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outstandingbalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='FeeCollections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uniqueid', models.CharField(max_length=10)),
                ('payment_reference', models.CharField(max_length=50)),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('school_code', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outstandingbalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('payment_mode', models.CharField(choices=[('mobile_wallet', 'Mobile Wallet'), ('Equity_bank_mobile_app', 'Equity Bank Mobile App'), ('Bank_cards', 'Bank Cards'), ('Bank_agent', 'Bank Agent'), ('Bank_over_the_counter', 'Banking Over the Counter')], max_length=50)),
                ('feecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feecategories.feecategories')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'verbose_name_plural': 'Fee Collections',
                'db_table': 'fee_collections',
            },
        ),
    ]
