# Generated by Django 4.2.13 on 2024-06-11 21:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expensetypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Expense Amount')),
                ('expenseID', models.CharField(default='TEMP', max_length=10, unique=True, verbose_name='Unique Expense ID')),
                ('datePosted', models.DateField(auto_now_add=True, verbose_name='Date Posted')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('receipt', models.FileField(blank=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Remaining Balance')),
                ('expensetypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expensetypes.expensetypes', verbose_name='Expense Type')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
    ]
