# Generated by Django 3.2.10 on 2024-03-04 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expensetypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('referenceNO', models.CharField(max_length=10)),
                ('expenseID', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('datePosted', models.DateField(auto_now_add=True)),
                ('expensetypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expensetypes.expensetypes')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
    ]
