# Generated by Django 3.2.10 on 2024-03-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensetypes', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(verbose_name='Expense Amount'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='datePosted',
            field=models.DateField(auto_now_add=True, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expenseID',
            field=models.CharField(max_length=10, unique=True, verbose_name='Unique Expense ID'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expensetypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expensetypes.expensetypes', verbose_name='Expense Type'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='referenceNO',
            field=models.CharField(max_length=10, unique=True, verbose_name='Reference Number (Optional)'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, verbose_name='Approval Status'),
        ),
    ]
