# Generated by Django 3.2.12 on 2024-04-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensetypes', '0002_alter_expensetypes_status'),
        ('expenses', '0002_auto_20240307_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expensetypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expensetypes.expensetypes', verbose_name='Expense Type'),
        ),
    ]
