# Generated by Django 3.2.10 on 2024-04-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensetypes', '0001_initial'),
        ('account', '0001_initial'),
        ('expenses', '0002_auto_20240307_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='debited_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='receipt',
            field=models.FileField(blank=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expensetypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expensetypes.expensetypes', verbose_name='Expense Type'),
        ),
    ]
