# Generated by Django 3.2.12 on 2024-04-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240425_0842'),
        ('expenses', '0003_alter_expenses_expensetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='debited_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='receipt',
            field=models.FileField(blank=True, upload_to='receipts/'),
        ),
    ]
