# Generated by Django 3.2.12 on 2024-05-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20240429_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expenses',
            name='payment_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
