# Generated by Django 3.2.12 on 2024-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20240522_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expense Amount'),
        ),
    ]
