# Generated by Django 3.2.12 on 2024-05-23 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20240523_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='referenceNO',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
