# Generated by Django 3.2.12 on 2024-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expenses_referenceno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, max_length=20),
        ),
    ]
