# Generated by Django 3.2.12 on 2024-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expenses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
