# Generated by Django 5.0.6 on 2024-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_expenses_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='expenseID',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='referenceNO',
        ),
        migrations.AddField(
            model_name='expenses',
            name='account_number',
            field=models.CharField(default=0, editable=False, max_length=20, unique=True, verbose_name='Account Number'),
        ),
    ]
