# Generated by Django 5.0.6 on 2024-05-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20240522_1419'),
        ('expenses', '0011_remove_expenses_expenseid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='debited_account',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='payment_details',
        ),
        migrations.AddField(
            model_name='expenses',
            name='expenseID',
            field=models.CharField(default='TEMP', max_length=10, unique=True, verbose_name='Unique Expense ID'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('reference_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('debited_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.expenses')),
            ],
            options={
                'db_table': 'expense_payments',
            },
        ),
    ]
