# Generated by Django 5.0.6 on 2024-05-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_remove_expenses_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
