# Generated by Django 5.0.6 on 2024-05-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_expenses_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Remaining Balance'),
        ),
    ]
