# Generated by Django 4.2.7 on 2024-05-29 06:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_expenses_remaining_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
