# Generated by Django 3.2.10 on 2024-04-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='parentID',
            new_name='parentIdno',
        ),
    ]
