# Generated by Django 3.2.10 on 2024-04-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_schoolid_students_schools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='schools',
            new_name='schoolID',
        ),
    ]
