# Generated by Django 3.2.25 on 2024-05-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('categorycode', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('grade', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary'), ('OTHER', 'Other')], max_length=100)),
                ('term', models.CharField(choices=[('Term1', 'Term1'), ('Term2', 'Term2'), ('Term3', 'Term3')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apply', models.CharField(choices=[('ALL', 'All'), ('OPTIONAL', 'OPTIONAL')], max_length=8)),
                ('datePosted', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'fee_categories',
            },
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feecategories.feecategories')),
            ],
        ),
    ]
