# Generated by Django 3.2.10 on 2024-04-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feecategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feecategories',
            options={},
        ),
    ]
