# Generated by Django 4.2.7 on 2024-05-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('parentIdno', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('firstLogin', models.CharField(default='Y', max_length=1)),
                ('deletedFlag', models.CharField(default='N', max_length=1)),
                ('status', models.IntegerField(default=0)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('parentType', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian'), ('Sponsor', 'Sponsor')], max_length=8)),
            ],
            options={
                'db_table': 'parents',
            },
        ),
    ]
