# Generated by Django 3.2.10 on 2024-04-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='accountno',
        ),
    ]
