# Generated by Django 4.2.7 on 2024-07-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='all_transactions',
        ),
    ]
