# Generated by Django 4.2.13 on 2024-06-11 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('account', '0003_auto_20240522_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('reference_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('debited_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.expenses')),
            ],
            options={
                'db_table': 'expense_payments',
            },
        ),
    ]
