# Generated by Django 4.2.13 on 2024-06-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensepayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepayment',
            name='destination_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='source_account',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
