
# Generated by Django 4.2.13 on 2024-06-14 10:39

# Generated by Django 4.2.13 on 2024-06-08 17:14


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsParents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('parentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parents')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],

            options={
                'db_table': 'studentsparents',
            },

        ),
    ]
