# Generated by Django 3.2.25 on 2024-05-26 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('feecategories', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeExtensions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_unique_id', models.CharField(max_length=50)),
                ('dueDate', models.DateField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_reminder_sent', models.DateField(blank=True, null=True)),
                ('reminder_frequency', models.IntegerField(default=3)),
                ('feecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feecategories.feecategories')),
                ('school_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fee_extensions',
            },
        ),
    ]
