# Generated by Django 4.2.7 on 2024-07-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
