# Generated by Django 3.2.10 on 2024-04-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_uniqueid'),
        ('payfee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='uniqueId',
        ),
        migrations.AlterField(
            model_name='payments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paymentmode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='reference',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students', to_field='uniqueId'),
        ),
    ]
